name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
    - uses: actions/setup-node@v1.4.2
      
    - name: Setup Node.js environment
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: 12  
    - name: Installing npm
      run: npm install -g surge
    - name: Deploying app using surge
      run: surge ./ rehmanali.surge.sh --token ${{ secrets.SURGE_TOKEN }}
